### ISSUE TITLE
Add support for templating without the need for files

### ISSUE THREAD

**Issue by allejo** [cuchi/jinja2-action#18]
I'd like to propose to add support for compiling templates without needing files. An example use case would be something along the lines of this,

```yaml
- id: pr-message
  name: Create PR Message
  uses: cuchi/jinja2-action@v1.2.2
  with:
    template_str: |
      Hello! You've created a PR that has {{ num_files_touched }} files changed!

      {% for file in files %}
        - {{ file }}
      {% endfor %}
    strict: true
    variables: |
      files=...
      num_files_touched=30
- name: Create PR
  uses: peter-evans/create-pull-request@v5
  with:
    body: ${{ steps.pr-message.outputs.contents }}
```

Would this be feasible? A major version bump might be necessary since `template` and `output_file` will no longer be required. If `output_file` is omitted, then it'd save the contents to the step's outputs? Not sure about the design for the variables.
